
# puppet forge modules
mod 'puppetlabs/apt'             , '7.4.1'
mod 'puppetlabs/stdlib'          , '6.4.0'
mod 'puppetlabs/concat'          , '6.2.0'
mod 'puppetlabs/postgresql'      , '6.7.0'
mod 'puppetlabs/translate'       , '2.2.0'